### ISSUE TITLE
Publish to nodejs/devcontainer rather than bnb/devenv

### ISSUE THREAD

**Issue by bnb** [nodejs/devcontainer#2]
presently, we're publishing the docker image to bnb/devenv on Docker Hub. Ideally, we'd be able to change that to publishing to nodejs/devcontainer on Docker Hub.

We'd need to add correct secrets (cc @nodejs/docker) to this repo, which would be consumed by the build and publish action [here](https://github.com/nodejs/devcontainer/blob/main/.github/workflows/docker-build-and-publish.yml#L19-L20).

Further, we'd want to update the tags [here](https://github.com/nodejs/devcontainer/blob/main/.github/workflows/docker-build-and-publish.yml#L26) to `nodejs/devcontainer:latest`.

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?

**Comment by bnb** [comment]
Just a note that this isn't stalled, we're just waiting on getting ownership of an organization :)

**Comment by bnb** [comment]
update: secrets are in the repo, action is running now. This *should* work.

**Comment by bnb** [comment]
done :)
